# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyProRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('rank', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('position', models.CharField(choices=[(b'QB', b'Quarterback'), (b'RB', b'Runningback'), (b'WR', b'Wide Receiver'), (b'TE', b'Tight End'), (b'DEF', b'Defense'), (b'K', b'Kicker')], max_length=3)),
                ('bye', models.IntegerField(null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('team', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
            options={
                'ordering': ['rank'],
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='Rotoworld_Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('roto_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
