# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiersheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Runningback'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('DEF', 'Defense'), ('K', 'Kicker')], max_length=3),
        ),
    ]
