# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiersheet', '0002_auto_20160713_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isStarred',
            field=models.BooleanField(default=False),
        ),
    ]
